apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: meu-projeto-docs
  description: Documentação do meu projeto
  annotations:
    github.com/project-slug: carlosrobertodevops/meu-projeto-docs
    backstage.io/techdocs-ref: dir:.
    backstage.io/view-url: https://github.com/carlosrobertodevops/meu-projeto-docs/blob/main/catalog-info.yaml
    backstage.io/edit-url: https://github.com/carlosrobertodevops/meu-projeto-docs/blob/main/catalog-info.yaml

spec:
  type: documentation
  owner: user:carlos
  lifecycle: production
  links:
  - url: https://github.com/carlosrobertodevops/meu-projeto-docs/blob/main/catalog-info.yaml
    title: Repositório GitHub
