#!/bin/bash

# Prepare
git clone "https://github.com/carlosrobertodevops/meu-projeto-docs.git"
cd repo

# Install @techdocs/cli, mkdocs and mkdocs plugins
npm install -g @techdocs/cli
pip install "mkdocs-techdocs-core==1.*"

unset AWS_PROFILE

# Generate
techdocs-cli generate --no-docker

# Publish
techdocs-cli publish \
	--publisher-type awsS3 \
	--storage-name $TECHDOCS_BUCKET \
	--entity $NAMESPACE/$KIND/$NAME

rm -rf "./meu-projeto-docs"
rm -rf "./site/"